using System;
using System.Collections.Generic;
using System.Text;

namespace Panuon.UI.Silver.Resources
{
    public static class ComponentKeys
    {
        public const string ButtonHelperPendingSpinnerStyle = nameof(ButtonHelperPendingSpinnerStyle);
        public const string ColorPickerClearButtonStyle = nameof(ColorPickerClearButtonStyle);
        public const string ColorPickerToggleArrowTransformControlStyle = nameof(ColorPickerToggleArrowTransformControlStyle);
        public const string ColorPickerColorSelectorStyle = nameof(ColorPickerColorSelectorStyle);
        public const string ColorSelectorDropperThumbStyle = nameof(ColorSelectorDropperThumbStyle);
        public const string ColorSelectorInputTextBoxStyle = nameof(ColorSelectorInputTextBoxStyle);
        public const string ColorSelectorSliderStyle = nameof(ColorSelectorSliderStyle);
        public const string ColorSelectorThumbFenceStyle = nameof(ColorSelectorThumbFenceStyle);
        public const string ComboBoxHelperClearButtonStyle = nameof(ComboBoxHelperClearButtonStyle);
        public const string ComboBoxHelperRemoveButtonStyle = nameof(ComboBoxHelperRemoveButtonStyle);
        public const string ComboBoxHelperToggleArrowTransformControlStyle = nameof(ComboBoxHelperToggleArrowTransformControlStyle);
        public const string ComboBoxHelperSearchTextBoxStyle = nameof(ComboBoxHelperSearchTextBoxStyle);
        public const string ContextMenuHelperMenuItemStyle = nameof(ContextMenuHelperMenuItemStyle);
        public const string DataGridHelperSelectAllButtonStyle = nameof(DataGridHelperSelectAllButtonStyle);
        public const string DataGridHelperSortArrowTransformControlStyle = nameof(DataGridHelperSortArrowTransformControlStyle);
        public const string DataGridHelperAutoGeneratedTextBoxStyle = nameof(DataGridHelperAutoGeneratedTextBoxStyle);
        public const string DataGridHelperAutoGeneratedComboBoxStyle = nameof(DataGridHelperAutoGeneratedComboBoxStyle);
        public const string DataGridHelperAutoGeneratedCheckBoxStyle = nameof(DataGridHelperAutoGeneratedCheckBoxStyle);
        public const string ExpanderHelperToggleArrowTransformControlStyle = nameof(ExpanderHelperToggleArrowTransformControlStyle);
        public const string ListBoxHelperRemoveButtonStyle = nameof(ListBoxHelperRemoveButtonStyle);
        public const string MessageBoxXWindowXStyle = nameof(MessageBoxXWindowXStyle);
        public const string MessageBoxXButtonStyle = nameof(MessageBoxXButtonStyle);
        public const string NoticeBoxNoticeBoxItemStyle = nameof(NoticeBoxNoticeBoxItemStyle);
        public const string PaginationTurnPageButtonStyle = nameof(PaginationTurnPageButtonStyle);
        public const string PaginationPaginationItemStyle = nameof(PaginationPaginationItemStyle);
        public const string PaginationOmittingTextBlockStyle = nameof(PaginationOmittingTextBlockStyle);
        public const string PasswordBoxHelperClearButtonStyle = nameof(PasswordBoxHelperClearButtonStyle);
        public const string PasswordBoxHelperPlainButtonStyle = nameof(PasswordBoxHelperPlainButtonStyle);
        public const string PendingBoxCancelButtonStyle = nameof(PendingBoxCancelButtonStyle);
        public const string PendingBoxSpinnerStyle = nameof(PendingBoxSpinnerStyle);
        public const string PendingBoxWindowStyle = nameof(PendingBoxWindowStyle);
        public const string RepeatButtonHelperPendingSpinnerStyle = nameof(RepeatButtonHelperPendingSpinnerStyle);
        public const string ScrollBarHelperScrollButtonStyle = nameof(ScrollBarHelperScrollButtonStyle);
        public const string SliderHelperThumbStyle = nameof(SliderHelperThumbStyle);
        public const string TabControlHelperRemoveButtonStyle = nameof(TabControlHelperRemoveButtonStyle);
        public const string TextBoxHelperClearButtonStyle = nameof(TextBoxHelperClearButtonStyle);
        public const string ThumbFenceThumbStyle = nameof(ThumbFenceThumbStyle);
        public const string ToggleButtonHelperPendingSpinnerStyle = nameof(ToggleButtonHelperPendingSpinnerStyle);
        public const string TreeViewHelperToggleArrowToggleButtonStyle = nameof(TreeViewHelperToggleArrowToggleButtonStyle);
        public const string WindowXCaptionMinimizeButtonStyle = nameof(WindowXCaptionMinimizeButtonStyle);
        public const string WindowXCaptionMaximizeButtonStyle = nameof(WindowXCaptionMaximizeButtonStyle);
        public const string WindowXCaptionCloseButtonStyle = nameof(WindowXCaptionCloseButtonStyle);
        public const string WindowXModalButtonStyle = nameof(WindowXModalButtonStyle);
    }
}
